# Generated by Django 4.0.2 on 2022-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('adress', models.TextField(null=True)),
                ('phonenumber', models.CharField(max_length=10, null=True, unique=True)),
                ('branch', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
